"""Initial migration

Revision ID: db88d07c7308
Revises: 
Create Date: 2025-06-03 11:04:05.058868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db88d07c7308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_name_cn', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_person_cn', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_cn', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('business_address', sa.JSON(), nullable=True),
    sa.Column('region', sa.Enum('ASIA_PACIFIC', 'NORTH_AMERICA', 'EUROPE', 'MIDDLE_EAST', 'AFRICA', 'SOUTH_AMERICA', name='region'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.JSON(), nullable=True),
    sa.Column('business_type', sa.JSON(), nullable=True),
    sa.Column('project_preferences', sa.JSON(), nullable=True),
    sa.Column('project_history', sa.JSON(), nullable=True),
    sa.Column('payment_info', sa.JSON(), nullable=True),
    sa.Column('bank_info', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='clientstatus'), nullable=False),
    sa.Column('last_contact', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('team_members',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Enum('MODELING', 'RENDERING', 'DESIGN', 'SALES', 'MANAGEMENT', name='department'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id_card', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('price_type', sa.Enum('FIXED', 'HOURLY', 'PROJECT', name='pricetype'), nullable=False),
    sa.Column('bird_view_price', sa.Float(), nullable=True),
    sa.Column('human_view_price', sa.Float(), nullable=True),
    sa.Column('animation_price', sa.Float(), nullable=True),
    sa.Column('custom_price', sa.Float(), nullable=True),
    sa.Column('bank_info', sa.String(length=500), nullable=True),
    sa.Column('payment_cycle', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='memberstatus'), nullable=False),
    sa.Column('current_projects', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'DESIGNER', 'MODELER', 'RENDERER', 'SALES', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('protocol_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REPORTING', 'MODELING', 'RENDERING', 'DELIVERING', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'AUD', 'CNY', 'CAD', 'GBP', 'SGD', 'AED', name='currency'), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('budget_cny', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_protocol_number'), 'projects', ['protocol_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_protocol_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ### 