"""Add relationships and update models

Revision ID: fcd97c8e23e7
Revises: db88d07c7308
Create Date: 2025-06-03 11:13:32.673404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd97c8e23e7'
down_revision = 'db88d07c7308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 